name: Release ZIP Build

on:
  release:
    types: [created]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from version.php
        run: |
          VERSION=$(grep -oP '\$plugin->version\s*=\s*\K\d+' version.php)
          echo "PLUGIN_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install Node.js dependencies
        run: npm install --production

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create versioned ZIP file
        run: |
          # Create a new directory for the plugin in the parent directory
          mkdir ../local_h5pcaretaker

          # Copy necessary files into the new directory
          cp -r ./* ../local_h5pcaretaker/ \
            && rm -rf ../local_h5pcaretaker/.github \
            && rm -rf ../local_h5pcaretaker/.git \
            && rm -rf ../local_h5pcaretaker/docs \
            && rm -f ../local_h5pcaretaker/composer.json \
            && rm -f ../local_h5pcaretaker/composer.lock \
            && rm -f ../local_h5pcaretaker/package.json \
            && rm -f ../local_h5pcaretaker/package-lock.json \
            && rm -f ../local_h5pcaretaker/.gitignore

          # Change to the parent directory to create the ZIP file
          cd ..
          # Create the ZIP file
          ZIP_NAME="moodle-local_h5pcaretaker-${{ env.PLUGIN_VERSION }}.zip"
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV
          zip -r "$ZIP_NAME" local_h5pcaretaker

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: "../${{ env.ZIP_NAME }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
